name: praying
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  pine: ^1.0.2
  provider: ^6.0.5
  auto_route: ^7.5.0
  animated_notch_bottom_bar: ^1.0.0
  font_awesome_flutter: ^10.5.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  auto_route_generator: ^7.1.1
  data_fixture_dart: ^2.2.0
  mockito: ^5.4.2
  bloc_test: ^9.1.3


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/preghiera.json

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
    - family: Ranchers
      fonts:
        - asset: assets/fonts/ranchers/Ranchers-Regular.ttf

